name: Package and Release

on:
  push:
    tags:
      - "v*"
      - "[0-9]+.*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare for packaging
        run: |
          # The packager needs the addon files in a specific structure
          # Copy everything from DamiaUI subfolder to root temporarily
          cp -r DamiaUI/* .
          # Keep the original DamiaUI folder for proper packaging
          
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -d

      - name: Upload Release Assets
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: ".release/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          allowUpdates: true
          updateOnlyUnreleased: false
          body: |
            ## DamiaUI ${{ github.ref_name }}
            
            ### What's New
            - Bug fixes and improvements
            - WoW 11.2+ compatibility updates
            
            ### Installation
            1. Download the appropriate zip file for your WoW version
            2. Extract to your `Interface/AddOns/` folder
            3. Restart World of Warcraft
            4. Enable DamiaUI in the AddOn menu
            
            ### Supported Versions
            - ✅ World of Warcraft 11.2+ (The War Within and newer)
            
            ### Getting Started
            - Type `/damiaui` in-game for configuration options
            - Visit our [GitHub repository](https://github.com/korallis/DamiaUI) for documentation
            
            ### Support
            If you encounter issues, please report them on our [Issues page](https://github.com/korallis/DamiaUI/issues).